### ISSUE TITLE
panic in code related to go-server-timing@v1.0.1/middleware.go

### ISSUE THREAD

**Issue by lidel** [ipfs/bifrost-gateway#72]
Seems to be related to library introduced in  #71  (not critical, seems to happen sporadically)

```
2023-04-03T19:17:38.277Z	ERROR	core/server	gateway/handler.go:319	A panic occurred in the gateway handler!
2023-04-03T19:17:38.277Z	ERROR	core/server	gateway/handler.go:320	runtime error: invalid memory address or nil pointer dereference
goroutine 323 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x19
github.com/ipfs/boxo/gateway.panicHandler({0x1229fe0, 0xc0006563c0})
	/go/pkg/mod/github.com/ipfs/boxo@v0.8.0-rc4/gateway/handler.go:321 +0xfc
panic({0xd2c760, 0x181bf40})
	/usr/local/go/src/runtime/panic.go:884 +0x212
github.com/ipfs/boxo/gateway.(*handler).serveCAR(0xc0008b0770, {0x122a690, 0xc002c010e0}, {0x1229fe0?, 0xc0006563c0}, 0xc0005350a8, {{0x122a8c0?, 0xc0003a4c60?}}, {0x122a8c0, 0xc0003a4c60}, ...)
	/go/pkg/mod/github.com/ipfs/boxo@v0.8.0-rc4/gateway/handler_car.go:87 +0xbc1
github.com/ipfs/boxo/gateway.(*handler).getOrHeadHandler(0xc0008b0770, {0x1229fe0, 0xc0006563c0}, 0xc0005352c8)
	/go/pkg/mod/github.com/ipfs/boxo@v0.8.0-rc4/gateway/handler.go:292 +0x13fa
github.com/ipfs/boxo/gateway.(*handler).ServeHTTP(0xc0008b0770, {0x1229fe0, 0xc0006563c0}, 0xc000339500)
	/go/pkg/mod/github.com/ipfs/boxo@v0.8.0-rc4/gateway/handler.go:167 +0x234
net/http.(*ServeMux).ServeHTTP(0xc000535478?, {0x1229fe0, 0xc0006563c0}, 0xc000339500)
	/usr/local/go/src/net/http/server.go:2487 +0x149
main.withConnect.func1({0x1229fe0?, 0xc0006563c0?}, 0xc002afc615?)
	/go/src/github.com/ipfs/bifrost-gateway/handlers.go:57 +0x73
net/http.HandlerFunc.ServeHTTP(0x122a690?, {0x1229fe0?, 0xc0006563c0?}, 0xc000b68f00?)
	/usr/local/go/src/net/http/server.go:2109 +0x2f
github.com/ipfs/boxo/gateway.WithHostname.func1({0x1229fe0, 0xc0006563c0}, 0xc000339500)
	/go/pkg/mod/github.com/ipfs/boxo@v0.8.0-rc4/gateway/hostname.go:241 +0x4e2
net/http.HandlerFunc.ServeHTTP(0x0?, {0x1229fe0?, 0xc0006563c0?}, 0x0?)
	/usr/local/go/src/net/http/server.go:2109 +0x2f
github.com/mitchellh/go-server-timing.Middleware.func1({0x7fade48c69f8, 0xc000656320}, 0xc000339400)
	/go/pkg/mod/github.com/mitchellh/go-server-timing@v1.0.1/middleware.go:74 +0x32b
net/http.HandlerFunc.ServeHTTP(0x1229320?, {0x7fade48c69f8?, 0xc000656320?}, 0xc0009b79a0?)
	/usr/local/go/src/net/http/server.go:2109 +0x2f
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerResponseSize.func1({0x1229320?, 0xc00183a380?}, 0xc000339400)
	/go/pkg/mod/github.com/prometheus/client_golang@v1.14.0/prometheus/promhttp/instrument_server.go:288 +0xc5
net/http.HandlerFunc.ServeHTTP(0xc0009b7a50?, {0x1229320?, 0xc00183a380?}, 0xc00081a6e0?)
	/usr/local/go/src/net/http/server.go:2109 +0x2f
main.withRequestLogger.func1({0x1229320, 0xc00183a380}, 0xc000339400)
	/go/src/github.com/ipfs/bifrost-gateway/handlers.go:65 +0x171
net/http.HandlerFunc.ServeHTTP(0xc00067a463?, {0x1229320?, 0xc00183a380?}, 0x46d96e?)
	/usr/local/go/src/net/http/server.go:2109 +0x2f
net/http.serverHandler.ServeHTTP({0xc000658630?}, {0x1229320, 0xc00183a380}, 0xc000339400)
	/usr/local/go/src/net/http/server.go:2947 +0x30c
net/http.(*conn).serve(0xc00041c280, {0x122a690, 0xc0009ca120})
	/usr/local/go/src/net/http/server.go:1991 +0x607
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:3102 +0x4db
```

**Comment by willscott** [comment]
the server-timing line in the stack trace seem to just be part of it's middle-ware pass through: https://github.com/mitchellh/go-server-timing/blob/0eeb78c285aedc6d1a54cc8d52057769e5c9397f/middleware.go#L74


can `err` on the line that's panic'ing be nil? https://github.com/ipfs/boxo/blob/v0.8.0-rc4/gateway/handler_car.go#L87

**Comment by lidel** [comment]
Deployed the fix (https://github.com/ipfs/boxo/pull/255)  to staging, panic is gone:

```
2023/04/03 20:42:03 Starting bifrost-gateway 2023-04-03-bfe2e6f
```
